import json

from fastapi import APIRouter, Depends

from api.dependencies import result_store
from productpulse.services.results import ResultStore

router = APIRouter()


@router.get("/retailrocket")
def retailrocket(store: ResultStore = Depends(result_store)):
    """
    Retailrocket behavior analytics from canonical results.
    """

    def optional_records(relative_path: str):
        path = store.path(relative_path)

        if not path.exists():
            return []

        return store.records(relative_path)

    return {
        "overview": optional_records(
            "retailrocket/behavior_overview.csv"
        ),
        "funnel": optional_records(
            "retailrocket/funnel_metrics.csv"
        ),
        "engagement": optional_records(
            "retailrocket/engagement_summary.csv"
        ),
        "result_source": "results/retailrocket",
    }


@router.get("/online-retail")
def online_retail(store: ResultStore = Depends(result_store)):
    """
    Dashboard-facing Online Retail II results.

    Canonical summary/split outputs come from:
        results/online_retail/

    Older notebook analytics are temporarily retained as
    supplemental dashboard tables.
    """

    summary_path = store.path(
        "online_retail/summary.json"
    )
    split_path = store.path(
        "online_retail/split_summary.csv"
    )

    summary = (
        json.loads(summary_path.read_text())
        if summary_path.exists()
        else {}
    )

    split_summary = (
        store.records(
            "online_retail/split_summary.csv"
        )
        if split_path.exists()
        else []
    )

    def optional_records(relative_path: str):
        path = store.path(relative_path)

        if not path.exists():
            return []

        return store.records(relative_path)

    return {
        "summary": summary,
        "split_summary": split_summary,

        "business_overview": optional_records(
            "04_online_retail_customer_product_analytics/"
            "tables/business_overview.csv"
        ),
        "customer_summary": optional_records(
            "04_online_retail_customer_product_analytics/"
            "tables/customer_summary.csv"
        ),
        "top_countries": optional_records(
            "04_online_retail_customer_product_analytics/"
            "tables/top_countries.csv"
        ),

        "result_source": "results/online_retail",
    }


@router.get("/experiment")
def experiment(store: ResultStore = Depends(result_store)):
    """
    Dashboard-facing Cookie Cats experiment results.

    Reads canonical outputs generated by:
        python -m productpulse run cookie-cats
    """

    retention_path = store.path(
        "cookie_cats/retention.csv"
    )
    rounds_path = store.path(
        "cookie_cats/rounds.json"
    )
    summary_path = store.path(
        "cookie_cats/summary.json"
    )

    retention = (
        store.records("cookie_cats/retention.csv")
        if retention_path.exists()
        else []
    )

    rounds = (
        json.loads(rounds_path.read_text())
        if rounds_path.exists()
        else {}
    )

    summary = (
        json.loads(summary_path.read_text())
        if summary_path.exists()
        else {}
    )

    decision = [
        {
            "metric": "retention_1",
            "action": summary.get(
                "retention_1_action"
            ),
        },
        {
            "metric": "retention_7",
            "action": summary.get(
                "retention_7_action"
            ),
        },
    ]

    return {
        "summary": summary,
        "retention": retention,
        "tests": retention,
        "rounds": rounds,
        "decision": decision,
        "result_source": "results/cookie_cats",
    }
